/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e01


/**
 * Searches the array for searchValue. Returns the first index where searchValue
 * is found. If not found, returns null.
 *
 * @param args array to be searched
 * @param searchValue value to be searched for
 * @return either index or null depending if searchValue was found
 */
fun search(args: Array<Int>, searchValue: Int) : Int? {
    val index = args.indexOf(searchValue)
    return if (index != -1) index else null
}

fun main(args: Array<String>) {
    println(search(arrayOf(1,2,3), 1))
}
