/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e02

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertFalse

class AppTest {
    @Test fun testIsPalindrome() {
        // True
        assertTrue("saippuakauppias".isPalindrome(), "saippuakauppias was NOT palindrome")
        assertTrue("saippuakauppiaS".isPalindrome(ignoreCase = true), "saippuakauppiaS was NOT palindrome")
        assertTrue("sai\nppua\tkau  ppias".isPalindrome(ignoreWhiteSpaces = true), "sai\nppua\tkau  ppias was NOT palindrome")
        assertTrue("sai\nppua\tkau  ppiaS".isPalindrome(ignoreCase = true, ignoreWhiteSpaces = true), "sai\nppua\tkau  ppiaS was NOT palindrome")

        // False
        assertFalse("Saippuakauppias".isPalindrome(), "Saippuakauppias was palindrome")
        assertFalse("sai\nppua\tkau  ppias".isPalindrome(ignoreCase = true, ignoreWhiteSpaces = false), "sai\nppua\tkau  ppiaS was palindrome")
        assertFalse("sai\nppua\tkau  ppiaS".isPalindrome(ignoreCase = false, ignoreWhiteSpaces = true), "sai\nppua\tkau  ppiaS was palindrome")
    }
}
