/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e01

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals
import kotlin.test.assertNull
// 
class AppTest {
    @Test fun testSearch() {
        // success
        val arr = arrayOf(1, 2, 3)
        assertEquals(0, search(arr, 1), "${arr.joinToString()}, search value 1 != with index 0")
        assertEquals(1, search(arr, 2), "${arr.joinToString()}, search value 2 != with index 1")
        assertEquals(2, search(arr, 3), "${arr.joinToString()}, search value 1 != with index 2")

        // fails
        assertNull(search(arr, -1), "${arr.joinToString()}, search value -1 != null")
        assertNull(search(arr, 5), "${arr.joinToString()}, search value 5 != null")
    }
}